import { Inter } from 'next/font/google'
import "./globals.css";
import { Metadata } from "next"
import { TopNavigation } from "@repo/ui/custom/navigation/top-navigation"
const inter = Inter({
  subsets: ["latin"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNavigation />
            {children}
        <div>Bottom Nav</div>
      </body>
    </html>
  );
}
