import localFont from "next/font/local";
import "@repo/ui/globals.css";
import { ThemeSwitcher } from "@repo/ui/components/ui/theme-switcher"
import { ThemeProvider } from "@repo/ui/components/ui/providers"
import { cn } from "@repo/ui/lib/utils"
import { Metadata, Viewport } from "next"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
            "min-h-screen bg-background font-sans antialiased"
          )}>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <div vaul-drawer-wrapper="">
              <div className="relative flex min-h-screen flex-col bg-background">
                {children}
              </div>
            </div>
        <ThemeSwitcher />

      </ThemeProvider>

      </body>
    </html>
  );
}
